server:
    port: 3000

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: "mongodb://localhost:27017/project4db"
      database: project4db

  webhook:
    url: "https://e5f8ff4a.ngrok.io"